name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats SVG
        uses: cicirello/user-statistician@v1
        with:
          image-file: "github-stats.svg"
          include-title: true
          custom-title: "SOC | IR | Automation | Data"
          colors: "00FF00,0077FF,00AAFF"
          animated-language-chart: true
          fail-on-error: true
          commit-and-push: true
          commit-message: "Update GitHub stats SVG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
