name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: DRA3V50
          template: classic
          base: header, activity
          config_timezone: America/Detroit

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 6

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_trophies: yes
          plugin_trophies_theme: onedark

      - name: Save metrics.svg
        run: |
          mkdir -p assets
          mv metrics.svg assets/metrics.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/metrics.svg
          git commit -m "Update metrics.svg" || echo "No changes"
          git push
