name: Local GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate stats SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: DRA3V50

          # Only show the simple stats card
          template: classic
          base: header, activity
          config_timezone: America/Detroit

          # Output
          output_action: commit
          output_path: assets/github-stats.svg
