name: Local GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: DRA3V50

          template: classic
          base: header, activity
          config_timezone: America/Detroit

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 6

          plugin_streak: yes

          output_action: commit
          output_path: assets/github-stats.svg
